Vagrant.configure("2") do |config|

  config.vm.define "DB_VM" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.hostname = "db.vm"
    db.vm.network "private_network", ip: "192.168.56.10"

    # Provisioning script to install and configure MySQL
    db.vm.provision "shell", inline: <<-SHELL
      # ENV

      export DB_USER="DB_USER"
      export DB_PASS="DB_PASS"
      export DB_NAME="DB_NAME"
      export DB_IP='192.168.56.10'
      export DB_PORT='3306'

      # Install MySQL
      sudo apt-get update
      sudo apt-get install -y mysql-server

      # Configure MySQL
      sudo sed -i "s/^bind-address\s*=.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
      sudo systemctl restart mysql

      # Create the database and user, and grant privileges
      sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
      sudo mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'$DB_IP' IDENTIFIED BY '$DB_PASS';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$DB_IP';"
      sudo mysql -e "FLUSH PRIVILEGES;"
    SHELL
  end


# App_vm 
  config.vm.define "APP_VM" do |app|
    app.vm.box = "ubuntu/bionic64"
    app.vm.hostname = "app.vm"
    app.vm.network "private_network", ip: "192.168.56.20"
    app.vm.network "forwarded_port", guest: 8080, host: 8080
    app.vm.provision "shell", inline: <<-SHELL

      export DB_USER='DB_USER'
      export DB_PASS='DB_PASS'
      export DB_NAME='DB_NAME'
      export DB_IP='192.168.56.10'
      export DB_PORT='3306'
      export PROJECT_DIR=/home/app_user/project

      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk git maven
      sudo useradd -m -s /bin/bash app_user
      
    SHELL
  end
end

