# Vagrantfile
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"  
  config.vm.hostname = "NginxTest"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "NginxTest"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx
      
      # Change port on 82

    sudo sed -i 's/listen 80 default_server;/listen 82 default_server;/' /etc/nginx/sites-available/default
    sudo sed -i 's/listen \[::\]:80 default_server;/listen [::]:82 default_server;/' /etc/nginx/sites-available/default

    # Change greeting
    echo "Everything done" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

    sudo systemctl restart nginx
  SHELL
end

